# Site settings
title: Dragon's Money Laundering
email: ilkka.hakkarainen@cs.helsinki.fi
description: > # this means to ignore newlines until "baseurl:"
  Dragon's Money Laundering is a card game that has minimalistic requirements, yet it provides fun and complex gaming experience for seasoned board-/cardgamers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://irkka.github.io/dml" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: Irkka

# Build settings
markdown: kramdown
